/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Paint;

/**
 *
 * @author RuDhLK
 */
public class CustomBackgroundJPanel extends javax.swing.JPanel {

   /**
    * Creates new form CustomBackgroundJPanel
    */
   public CustomBackgroundJPanel() {
      initComponents();
   }

   @Override
   protected void paintComponent(Graphics g) {
      super.paintComponent(g);
      Graphics2D g2d=(Graphics2D) g;
      //g2d.setPaint(new GradientPaint(getWidth()/2, 0, new Color(106, 0, 255), getWidth()/2, getHeight()/2, new Color(255, 255, 0255, 0)));
      g2d.setColor(new Color(106, 0, 255));
      g2d.fillRect(0, 0, getWidth(), getHeight());
      g2d.setColor(new Color(255, 255, 0255, 0));
      g2d.fillOval(0-50, 0, 100, getHeight());
      g2d.fillOval(getWidth()-50, 0, 100, getHeight());
   }

   
   /**
    * This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 400, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 300, Short.MAX_VALUE)
      );
   }// </editor-fold>//GEN-END:initComponents
   // Variables declaration - do not modify//GEN-BEGIN:variables
   // End of variables declaration//GEN-END:variables
}
